name: OurTube-development

services:
  minio:
    env_file:
      - .env.development
    ports:
      - "9000:9000"
      - "9090:9090"

  postgres:
    env_file:
      - .env.development
    ports:
      - "5432:5432"