version: '3.9'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API 
      - "9090:9090"   # Консоль 
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_SERVER_URL: "http://0.0.0.0:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://0.0.0.0:9090"
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ourtube-api:
    build:
      context: ../backend/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DATAPROTECTION__KEYSPATH=/root/.aspnet/DataProtection-Keys
      - AllowedHosts=${ALLOWED_HOSTS}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - SMTP__Server=${SMTP__Server}
      - SMTP__Port=${SMTP__Port}
      - SMTP__Email=${SMTP__Email}
      - SMTP__Password=${SMTP__Password}
      - Minio__AccessKey=${MinIO__AccessKey}
      - Minio__SecretKey=${MinIO__SecretKey}
      - Minio__Endpoint=${MinIO__Endpoint}
      - Minio__VideoBucket=${MinIO__VideoBucket}
      - Minio__UserBucket=${MinIO__UserBucket}
      - FFmpeg__ExecutablesPath=${FFmpeg__ExecutablesPath}
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
        
volumes:
  minio_data:
  postgres_data:
  data-protection-keys:
    
